<?php

// Global Actions
defined('ACTION_NONE') or define('ACTION_NONE', 0);
defined('ACTION_DOWNLOAD_BOOKLET') or define('ACTION_DOWNLOAD_BOOKLET', 1);
defined('ACTION_UPLOAD_BOOKLET') or define('ACTION_UPLOAD_BOOKLET', 2);
defined('ACTION_SENDING_BOOKLET_FILE') or define('ACTION_SENDING_BOOKLET_FILE', 3);
defined('ACTION_ADD_COURSE') or define('ACTION_ADD_COURSE', 4);
defined('ACTION_ADD_TEACHER') or define('ACTION_ADD_TEACHER', 5); // EXTRA ACTION VALUE (TEACHER ID/COURSE_ID/ETC.)
defined('ACTION_WHISPER_GODS_NAME') or define('ACTION_WHISPER_GODS_NAME', 6);
defined('ACTION_WHISPER_GODS_SECRET') or define('ACTION_WHISPER_GODS_SECRET', 7);
defined('ACTION_SELECT_BOOKLET_TO_GET') or define('ACTION_SELECT_BOOKLET_TO_GET', 8);
defined('ACTION_WRITE_MESSAGE') or define('ACTION_WRITE_MESSAGE', 9);
defined('ACTION_WRITE_REPLY_TO_USER') or define('ACTION_WRITE_REPLY_TO_USER', 10);
defined('ACTION_ADD_ADMIN') or define('ACTION_ADD_ADMIN', 11);
defined('ACTION_DOWNGRADE_USER') or define('ACTION_DOWNGRADE_USER', -1);
defined('ACTION_ASSIGN_USER_NAME') or define('ACTION_ASSIGN_USER_NAME', 12);
defined('ACTION_SET_BOOKLET_CAPTION') or define('ACTION_SET_BOOKLET_CAPTION', 13);
defined('ACTION_EDIT_BOOKLET_CAPTION') or define('ACTION_EDIT_BOOKLET_CAPTION', 14);
defined('ACTION_SEND_POST_TO_CHANNEL') or define('ACTION_SEND_POST_TO_CHANNEL', 16);
defined('ACTION_EDIT_BOOKLET_FILE') or define('ACTION_EDIT_BOOKLET_FILE', 17);
defined('ACTION_LINK_TEACHER') or define('ACTION_LINK_TEACHER', 18);
defined('ACTION_SELECT_TEACHER_TO_CONTACT') or define('ACTION_SELECT_TEACHER_TO_CONTACT', 19);
defined('ACTION_SELECT_BOOKLET_TO_EDIT') or define('ACTION_SELECT_BOOKLET_TO_EDIT', 15);
defined('ACTION_ADD_TA') or define('ACTION_ADD_TA', 20);
defined('ACTION_SEND_NOTIFICATION') or define('ACTION_SEND_NOTIFICATION', 21);
defined('ACTION_INTRODUCE_TEACHER') or define('ACTION_INTRODUCE_TEACHER', 22);
defined('ACTION_SEE_TEACHER_BIOS') or define('ACTION_SEE_TEACHER_BIOS', 23);
defined('ACTION_UPLOAD_SAMPLE') or define('ACTION_UPLOAD_SAMPLE', 24);
defined('ACTION_SENDING_SAMPLE_FILE') or define('ACTION_SENDING_SAMPLE_FILE', 25);
defined('ACTION_SET_SAMPLE_TITLE') or define('ACTION_SET_SAMPLE_TITLE', 26);
defined('ACTION_DOWNLOAD_SAMPLE') or define('ACTION_DOWNLOAD_SAMPLE', 27);



// Inline actions
defined('IA_CHECK_MEMBERSHIP') or define('IA_CHECK_MEMBERSHIP', 20);
defined('IA_SHOW_MESSAGE') or define('IA_SHOW_MESSAGE', 1);
defined('IA_REPLY_MESSAGE') or define('IA_REPLY_MESSAGE', 2);
defined('IA_LIST_FAVORITES') or define('IA_LIST_FAVORITES', 3);
defined('IA_GET_BOOKLET') or define('IA_GET_BOOKLET', 4);
defined('IA_GET_SAMPLE') or define('IA_GET_SAMPLE', 5);
defined('IA_DOWNGRADE_ADMIN') or define('IA_DOWNGRADE_ADMIN', 6);
defined('IA_REMOVE_TA') or define('IA_REMOVE_TA', 7);
defined('IA_CONTACT_TEACHER') or define('IA_CONTACT_TEACHER', 8);
defined('IA_LIST_SAMPLES') or define('IA_LIST_SAMPLES', 9);
defined('IA_UPLOAD_SAMPLE') or define('IA_UPLOAD_SAMPLE', 10);
defined('IA_UPLOAD_BOOKLET') or define('IA_UPLOAD_BOOKLET', 11);
defined('IA_LIST_BOOKLETS') or define('IA_LIST_BOOKLETS', 12);
defined('IA_EDIT_BOOKLET_CAPTION') or define('IA_EDIT_BOOKLET_CAPTION', 13);
defined('IA_EDIT_BOOKLET_FILE') or define('IA_EDIT_BOOKLET_FILE', 14);
defined('IA_SELECT_TEACHER_OPTIONS') or define('IA_SELECT_TEACHER_OPTIONS', 15);
defined('IA_SET_CAPTION') or define('IA_SET_CAPTION', 16);

// extra
defined('IAX_ADD_TO_FAVORITES') or define('IAX_ADD_TO_FAVORITES', 4);
defined('IAX_REMOVE_FROM_FAVORITES') or define('IAX_REMOVE_FROM_FAVORITES', -4);
